### ISSUE TITLE
如何在页面内请求其他地址的公共API？

### ISSUE THREAD

**Issue by AFAP** [daxiongYang/renren-fast-vue#10]
你好，请问在部分页面，如何实现其他域名地址的api访问呢？按照说明设置了代理那个打开，并不行，target那个看不懂……

**Comment by daxiongYang** [comment]
1. 代理是为了处理跨域问题哦。
2. 部分页面实现其他域名地址api访问？我理解是：默认大部分使用config/index.js中的window.SITE_CONFIG.baseUrl变量api请求，还存在部分请求是其他的地址吗？
    - 可以在api/modules/业务.js中 return request(url: 这里不要使用requestUrl()获取api请求地址，改为你想要的其他api请求地址)
   - 要做成可扩展的就多加配置参数，在api/requestUrl.js里面进行逻辑处理

**Comment by AFAP** [comment]
好的，谢谢
