### ISSUE TITLE
dialog中Tab组件错位

### ISSUE THREAD

**Issue by qriv** [daxiongYang/renren-fast-vue#12]
![issue](https://user-images.githubusercontent.com/10394578/39232060-ab26f012-489e-11e8-9f9a-d5eb07bedc55.png)
左边的菜单栏折叠时， 对话框中的Tab组件会位移。 原因是受到 css样式 影响
  .site-content--tabs > .el-tabs .el-tabs__header {
    left: 64px;
  }

**Comment by daxiongYang** [comment]
你好，这个bug已经修复的，请更新最新代码。
版本如果不方便更新，请在样式.class选择符中加上子选中符（比如 .site-content--tabs > .el-tabs > .el-tabs__header）避免影响 其它子级！！最新代码是这样的：
![image](https://user-images.githubusercontent.com/29277125/39244174-742c01c8-48c2-11e8-9ca2-97daa0862810.png)

**Comment by qriv** [comment]
😃 找不到更新的代码。。在哪个branch 里？

**Comment by daxiongYang** [comment]
master

**Comment by qriv** [comment]
我拉了最新代码，还是没有修复这个问题。![issue2](https://user-images.githubusercontent.com/10394578/39393807-3fa84736-4afc-11e8-8a9f-42d388157de5.png)
