### ISSUE TITLE
1.2 新版本的导航栏Tab有错

### ISSUE THREAD

**Issue by qriv** [daxiongYang/renren-fast-vue#14]
1. 打开多个窗口后，点击Tab 上的X关闭全部窗口
2. 重新打开任意一个窗口，导航栏Tab会同时打开两个窗口。 

应该是点击Tab 关闭窗口时，有缓存没有清空。
上次那个issue 好像关闭了， 问题还在，我更新了内容

**Comment by daxiongYang** [comment]
抱歉，之前的问题我给关闭了，是这个对吗？https://github.com/daxiongYang/renren-fast-vue/issues/12
我这边开发测试是ok的，之前群里有同学也遇到这个bug，我临时紧急修复的！同学更新表示也ok的。
![image](https://user-images.githubusercontent.com/29277125/39524662-3927fbc4-4e4c-11e8-8e5d-2c7153f0222d.png)
能否帮我多提供一点信息，让我更方便定位问题！！比如：看下元素是那个样式引起冲突的等

**Comment by qriv** [comment]
@daxiongYang  将左边的菜单缩小，在打开新增窗口。就能看到窗口内的tab位置错误。
![issue3](https://user-images.githubusercontent.com/10394578/39556159-d325f758-4eb0-11e8-8f4a-f70f0fc0480c.png)

**Comment by qriv** [comment]
@daxiongYang 这个是css样式选择的问题。解决了。文件_base.scss 如图
![1](https://user-images.githubusercontent.com/10394578/39558132-c5c32726-4ebe-11e8-9515-951d7f9ac1e0.png)
改成
![2](https://user-images.githubusercontent.com/10394578/39558141-cb973232-4ebe-11e8-8b05-6b9695689abf.png)

**Comment by qriv** [comment]
@daxiongYang  这个bug 1.20更新后出现的，需要解决
重现方式：
1.打开多个窗口后，点击Tab 上的X关闭全部窗口
2.重新打开任意一个窗口，导航栏Tab会同时打开两个窗口。

**Comment by daxiongYang** [comment]
@qriv 打开多个窗口后，这个窗口是指浏览器多窗口打开项目再打开多个tab，还是项目打开多个tab？
我测试了我复述的2种请求都未重现你说的问题。请帮忙提供详细描述，谢谢！

**Comment by qriv** [comment]
@daxiongYang 好意思，我指的窗口是指项目多个tab。

**Comment by daxiongYang** [comment]
@qriv 测试并没有重现，mac chrome 66.0.3359.139
