### ISSUE TITLE
新增管理员时候密码验证过不去

### ISSUE THREAD

**Issue by persistChao** [daxiongYang/renren-fast-vue#15]
在增加管理员的时候，填写所以表单后，点击提交，提示密码不能为空

**Comment by daxiongYang** [comment]
您好，测试未能复现你说的问题。请帮忙提供更多信息，定位问题！
![image](https://user-images.githubusercontent.com/29277125/39674308-7aa03606-517c-11e8-88c3-592430262417.png)

**Comment by daxiongYang** [comment]
这里问题已确认。是后台错误，请拉取最新后台代码。
