### ISSUE TITLE
npm run dev 报错， 无法部署

### ISSUE THREAD

**Issue by ruitobe** [daxiongYang/renren-fast-vue#16]
npm run dev 之后报错：
ERROR  Failed to compile with 1 errors                                 13:26:15

This relative module was not found:

./element-#17b3a3/index.css in ./src/element-ui-theme/index.js
在最新的这个commit 上面：
commit 4cbc577f487c839cf82c6cd895b925954b9590b6

OS: Ubuntu 14.04

node -v
v8.11.1

npm -v
5.6.0

**Comment by daxiongYang** [comment]
您好，项目开发环境还在用node v6.9.0，您说的问题我已经用nvm安装最新稳定node版本v8.11.1是存在的！
建议您先nvm安装v6.9.0的node版本暂时开发使用，因为项目中存在插件也依赖node版本的情况！！下个小版本会同步更新至node最新稳定版本！

**Comment by daxiongYang** [comment]
node已提交更新至v8.11.1，并未重现您的bug！
出现的是node-sass版本不兼容问题，已解决。

**Comment by ruitobe** [comment]
谢谢，现在最新版本没有报错，但是登录页面没有跳转。

**Comment by daxiongYang** [comment]
登录请求成功，又返回登录页bug已经修复（这个bug只有demo存在，因为后台为了方便大家演示测试，将单点登录给放开，支持多人同时登录一个账号，引起的bug）本地下载代码运行是不会出现此bug的！
