### ISSUE TITLE
添加新的菜单后，手动刷新，一直卡住，需要清楚缓存后再刷新可使用

### ISSUE THREAD

**Issue by ldw4033** [daxiongYang/renren-fast-vue#2]

**Comment by daxiongYang** [comment]
您好，能否详细描述您所遇到的问题步骤，最好配上浏览器F12控制台截图！因为我这边本地测试并没有您的问题出现。
![image](https://user-images.githubusercontent.com/29277125/37190315-16112a30-2394-11e8-8aa3-73058fb66a20.png)
