### ISSUE TITLE
楼主大大为什么不用iview开发一套呢，我觉得iview页面样式比现在这个好看多了

### ISSUE THREAD

**Issue by fuwei54321** [daxiongYang/renren-fast-vue#20]
![1525965770 1](https://user-images.githubusercontent.com/13740941/39877691-28e3da18-54a9-11e8-8a4a-9bac95b5e636.jpg)
![1525965789 1](https://user-images.githubusercontent.com/13740941/39877697-2c8c7422-54a9-11e8-8b46-132324c4e14a.jpg)

**Comment by daxiongYang** [comment]
没有太多为什么哦，只是简单的熟悉那个用那个，element-ui 1.x就开始用了！
如果楼主大大觉得iview漂亮，👏欢迎提供iview版本哦。
