### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by QuantSeven** [daxiongYang/renren-fast-vue#25]
![qq 20180528115425](https://user-images.githubusercontent.com/4331638/40596513-f6ad2d88-626d-11e8-8347-d8c6eb8f6b8c.png)

**Comment by QuantSeven** [comment]
![12](https://user-images.githubusercontent.com/4331638/40598787-5bc90512-627c-11e8-8006-b6877890d7f2.png)
这个是已经安装完成了的啊

**Comment by daxiongYang** [comment]
最新vue-cli提交代码引起的bug，请根据链接中提供的解决方法处理。https://github.com/vuejs/component-compiler-utils/issues/14
之后考虑用yarn.lock锁定版本，避免这类问题。
