### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by elite2013** [daxiongYang/renren-fast-vue#26]
npm ERR! path /usr/local/lib/node_modules/cnpm/node_modules/aws4
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/cnpm/node_modules/aws4'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules/cnpm/node_modules/aws4'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/cnpm/node_modules/aws4\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/cnpm/node_modules/aws4' }
npm ERR!

deprecate gulp@3.9.1 › gulp-util@^3.0.0 gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
deprecate gulp@3.9.1 › vinyl-fs@0.3.14 › graceful-fs@^3.0.0 please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
deprecate gulp@3.9.1 › vinyl-fs@0.3.14 › glob-stream@3.1.18 › minimatch@^2.0.1 Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
deprecate gulp@3.9.1 › vinyl-fs@0.3.14 › glob-watcher@0.0.6 › gaze@0.5.2 › globule@0.1.0 › minimatch@~0.2.11 Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
deprecate gulp@3.9.1 › vinyl-fs@0.3.14 › glob-watcher@0.0.6 › gaze@0.5.2 › globule@0.1.0 › glob@3.1.21 › graceful-fs@~1.2.0 please upgrade to

**Comment by daxiongYang** [comment]
#25
