### ISSUE TITLE
vendor.js打包文件过大，导致第一次加载特别慢，有解决方案吗？

### ISSUE THREAD

**Issue by curiohxx** [daxiongYang/renren-fast-vue#27]

**Comment by daxiongYang** [comment]
感谢你的关注！你提到的问题其实我也一直在找解决方案，目前并未找到理想的。因为项目依赖vue + vue-router + vux + axios + element-ui + vue-cookie，不管怎么优化（压缩、异步加载）文件大小摆在这里！！

建议：先服务器开启GZIP压缩，再cdn加速。这样可以大大减少文件大小，加快响应速度。

网上方案：使用DLL，将常用不怎么变更的文件打入一个统一的文件，cdn外链使用或直接通过webpack externals引用外部cdn文件的方式引入，效果是将vendor拆开2个或多个文件使用cdn加速。

如果你找到合适的解决方案，也请告诉我下，谢谢。

**Comment by ruiyong-lee** [comment]
我们感觉是路由的加载方式倒置了
![image](https://user-images.githubusercontent.com/12726826/43238693-d3ee669a-90c1-11e8-8657-d148c43c5814.png)
![image](https://user-images.githubusercontent.com/12726826/43238717-ef042a78-90c1-11e8-8bef-5799c401d925.png)
