### ISSUE TITLE
为什么登陆说账号已被锁定

### ISSUE THREAD

**Issue by Maipiao** [daxiongYang/renren-fast-vue#3]
是账号不能用了吗

**Comment by daxiongYang** [comment]
目前项目默认api请求地址为demo地址：//demo.renren.io/renren-fast，可能当时访问时被其他开发者将账号多次登录失败，给锁定了！！

本地开发请修改api请求地址（之后会提供mock本地数据模拟功能。敬请期待！！）
![image](https://user-images.githubusercontent.com/29277125/37334705-97364ec8-26e7-11e8-8306-46bef98a24bb.png)
