### ISSUE TITLE
角色和菜单的关联关系配置

### ISSUE THREAD

**Issue by hongliangpan** [daxiongYang/renren-fast-vue#33]
怎样配置 角色能访问哪些菜单？
![image](https://user-images.githubusercontent.com/4516326/41037603-533acbdc-69c6-11e8-86ad-9c57300b77a0.png)

**Comment by daxiongYang** [comment]
这是个bug，已经修复的。https://github.com/daxiongYang/renren-fast-vue/commit/8000491330e90da1a673f5936c97148f56a759d1
