### ISSUE TITLE
Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)

### ISSUE THREAD

**Issue by istroy** [daxiongYang/renren-fast-vue#34]
Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (64)

删掉模块，重新install还是这样

**Comment by daxiongYang** [comment]
此次大部分是有nodejs版本与node-sass版本不匹配。你需要更新下nodejs，或者删除模块，找到并安装nodejs版本对应的node-sass版本。
`"engines": {
    "node": ">= 8.11.1",
    "npm": ">= 5.6.0"
  }`
亲，这种问题搜索引擎很容易早到答案的。

**Comment by istroy** [comment]
非常感谢
