### ISSUE TITLE
打包方式是否跟踪相对路径 不用发布测试和线上的时候修改api接口地址

### ISSUE THREAD

**Issue by jyx12138** [daxiongYang/renren-fast-vue#36]

**Comment by daxiongYang** [comment]
抱歉，不是很明白您说的问题。

**Comment by jyx12138** [comment]
再jenkins上每次打包发布测试，预发，线上环境的时候，都需要在static/config/index-prod 文件内修改api的接口请求地址之后才可以么？

**Comment by daxiongYang** [comment]
并不需要每次修改呢！
 - 开发的时候，如果已经知道多个环境配置信息，就可以直接将预留index-[qa/uat/prod].js 3个配置文件信息填写完毕，然后在打包的时候，会自动根据命令参数打包生成对应配置信息文件的。
- 开发的时候，如果不知道多个环境配置信息，可以先用npm run build 打包命令。再修改dist/config/index.js文件中配置信息也是一样的。

**Comment by jyx12138** [comment]
嗯 好的 多谢！！！
