### ISSUE TITLE
npm install时报错Failed at the chromedriver@2.27.2 install script.

### ISSUE THREAD

**Issue by maozhiling2018** [daxiongYang/renren-fast-vue#37]
![image](https://user-images.githubusercontent.com/40971421/42428137-cd2740e4-8364-11e8-8cfc-9b58ca831584.png)

**Comment by zhoujin798946620** [comment]
这是vue通用的bug，npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver

**Comment by maozhiling2018** [comment]
@zhoujin798946620 ,非常感谢！
