### ISSUE TITLE
请问下这种自定义的html标签是在哪里定义的?<config> <add-or-update> 

### ISSUE THREAD

**Issue by Xusheng94** [daxiongYang/renren-fast-vue#4]
我按照你的方式进行扩展，然后写一个点击打开对话框的function this.viewbuslogVisible = true
        this.$nextTick(() => {
          this.$refs.viewbuslog.init(row)
        })  总是控制台提示 $refs.viewbuslog underfined 
![image](https://user-images.githubusercontent.com/19499563/37643908-036018ac-2c5d-11e8-9355-d103a81ff498.png)

**Comment by daxiongYang** [comment]
this.$refs 获取所有已注册的ref组件对象，需要在组件中绑定ref属性。
从现在的代码量无法很好定位问题，需要你提供更多的代码片段！

**Comment by Xusheng94** [comment]
好的，非常感谢，我全局搜索了具体的标签，好像没找到，可以具体说下在那个js里面import进去的吗

**Comment by Xusheng94** [comment]
![image](https://user-images.githubusercontent.com/19499563/37658860-77cc2b00-2c89-11e8-8d2a-159988aca201.png)
具体应该是标红的两个地方有问题

**Comment by daxiongYang** [comment]
从截图中并未看出哪里代码存在问题。如还无法解决，请在Q组里@我！
