### ISSUE TITLE
keepAlive

### ISSUE THREAD

**Issue by luhuilian123** [daxiongYang/renren-fast-vue#40]
为什么这里设置了<keep-alive include=""></keep-alive>不起作用，还是无法对指定组件实现缓存？？？急求，找1天了也没找到方法我在其他项目里使用keepAlive就可以，很正常，在这里不行，是哪里配置了什么吗？？
![_20180725195231](https://user-images.githubusercontent.com/41684432/43199373-4db85c84-9044-11e8-9767-385327e6c8f4.png)

**Comment by daxiongYang** [comment]
请问你在app.vue这里keep-alive是要将整个项目缓存？
还有就是请注意查看@/views/main-content.vue里面，已经使用keep-alive。
