### ISSUE TITLE
保存角色接口/sys/role/save，menuId存在-666666

### ISSUE THREAD

**Issue by LFHSEU** [daxiongYang/renren-fast-vue#42]
{"t":1533201409287,"roleName":"test","remark":"test","menuIdList":[1,2,15,16,17,18,3,19,20,21,22,4,23,24,25,26,5,6,7,8,9,10,11,12,13,14,27,29,30,-666666]}

**Comment by daxiongYang** [comment]
这个是为了处理 element tree组件选中id 和 后台保存有出入的问题，写的Hack。
你可以移除通过tempKey做的相关处理，来看效果。
