### ISSUE TITLE
动态路由的component 不能设置成功

### ISSUE THREAD

**Issue by dogodo-cc** [daxiongYang/renren-fast-vue#46]
你好，我按照你的方式const _import = require('./import-' + process.env.NODE_ENV) ，然后用route['component'] = _import(route.src) || null;去给路由添加component字段，可是一直都加载不成功。能指导下是否还需要其他配置呢

**Comment by daxiongYang** [comment]
const _import = require('./import-' + process.env.NODE_ENV) 这种方式建议不要使用了。下个版本是直接用vue-cli 3.0+ 那么webpack也是使用4.0+版本，你可以直接route['component'] = () => import(`@/views/modules/${route.src}`)
