### ISSUE TITLE
退出之后重新登录加载路由的时候控制台会提示有重复的路由

### ISSUE THREAD

**Issue by yc850903** [daxiongYang/renren-fast-vue#49]
退出之后登录系统增加的动态路由没有清楚再加载页面的时候导致控制台出现重复路由的警告。

[vue-router] Duplicate named routes definition: { name: "sys-user", path: "/sys-user" }

**Comment by yc850903** [comment]
在退出，路由跳转到login的回调方法里面刷新url是否可行？
this.$router.push({ name: 'login' }, () => {
                location.reload() // 刷新页面, 清空整站临时存储数据
              })

**Comment by daxiongYang** [comment]
重复路由警告这个开发环境提示，生产环境不会提示。暂时没找到合适的办法处理！但是刷新是可以解决的！可刷新会出现闪烁白屏。所以现在退出使用了clearLoginInfo方法，清除vuex store和token之内的登录信息。

**Comment by yc850903** [comment]
谢谢 楼主回答，但是我还想问个问题，为什么生产环境就不会出现重复路由的警告呢？我看代码也没有加特殊的控制啊。

**Comment by daxiongYang** [comment]
这个就跟vue类似，会存在多个版本。比如vue.js／vue.runtime.js／vue.min.js等...在webpack.base.conf.js里面就能看到开发环境用的vue.esm.js版本。而vue-router内部应该也是根据环境做了处理，在生产环境下忽略提示信息。

**Comment by yc850903** [comment]
其实这个路由重复了不会造成跳转异常的情况，只是会有个警告而已，我这样理解对吗？

**Comment by daxiongYang** [comment]
是的，具体内部怎么实现我未看过源码。
