### ISSUE TITLE
怎么进行页面跳转？

### ISSUE THREAD

**Issue by jinfang134** [daxiongYang/renren-fast-vue#5]
比如单独的编辑页面，router应该怎么写？

**Comment by daxiongYang** [comment]
1. 编辑页面，一般是通过列表或者其他展示页面操作打开。所有个人建议使用弹窗！
2. 项目中所有路由都在router/index.js中配置（独立打开tab标签页 参考404／login路由，需要tab标签页打开 参考管理员管理／菜单管理等路由...）。
3. 路由中有说明建议，通过url访问使用path属性访问（这个也是真实对外路由），代码中跳转使用name属性。
4. vue-router api参考资料：https://router.vuejs.org/zh-cn/

**Comment by jinfang134** [comment]
> 1. 编辑页面，一般是通过列表或者其他展示页面操作打开。所有个人建议使用弹窗！
当要编辑的内容很复杂，内容很多，甚至要分好几个页面来编辑的时候，弹窗显然就不太合适了。可否用子路由来做？

**Comment by jinfang134** [comment]
当前的逻辑是，只要是有链接，就一定会出现在左边的 `sidebar` 里，而我的建议是能不能加一个 `hide` 的meta属性在路由表里，这样 可以有链接，但是不出现在左边的 `sidebar` 里

**Comment by jinfang134** [comment]
比如类似订单管理的页面，我要查看某个订单的详情，但是 弹窗可能显示不下，就需要跳到另外一个页面，但是这个页面是带参数的，他不应该出现在左侧的 `sidebar` 里，所以需要在左侧隐藏。

**Comment by daxiongYang** [comment]
1. 首先，想先了解您所说的子路由是怎样的？
    - 我的理解：/#/n/user是用户管理页面，你想通过/#/n/user/:id路由实现用户管理编辑页面功能？
    - 如果我的理解是对的，这个编辑页面需要如何展示？同时编辑页面是否允许通过url直接可以访问权限？
2. 个人建议只允许直接访问的页面才提供路由，而内部逻辑页面通过组件v-if来实现。同时您提到的内容很复杂很多，弹窗中可以开tab标签（图为公司内部菜单！）。
![image](https://user-images.githubusercontent.com/29277125/37808708-cecab62a-2e86-11e8-8a94-bc52bf609929.png)
3. 如我说的并不能满足您提出自路由的需求，可以在router配置这个增加路由。这样就跟首页一样，不会添加在tab标签页中！
![image](https://user-images.githubusercontent.com/29277125/37808479-8ee67cb6-2e85-11e8-8a90-9bb334e38372.png)
4. 这里有个问题需要提及下，项目中拦截了/n/做为左侧菜单打开内容tab标签页功能。如想直接这样/#/n/user/:id开子路由，是访问不了的！！

**Comment by jinfang134** [comment]
谢谢您的耐心解答，我大概明白了，我想实现的是类似查看订单详细的功能，想在单独一个页面里展示，这样就算用户刷新也不会影响。但是不应该出现在左侧菜单里面。

**Comment by jinfang134** [comment]
其实我觉得可以在路由表里加一个`hide` 的 meta 属性来实现，在左侧菜单渲染的时候，不渲染 `hide` 的路由，您觉得呢？

**Comment by daxiongYang** [comment]
抱歉！由于之前是在实现fast项目前端功能，导致未能将路由考虑周全。现在已支持子路由功能，通过meta: { isTab: true }属性，设定是否通过tab标签页展示内容。另外左侧菜单是通过后台返回渲染的。
