### ISSUE TITLE
怎么同时执行多个请求?

### ISSUE THREAD

**Issue by cnsimplo** [daxiongYang/renren-fast-vue#50]
老大, 这种怎么一次执行多个请求?请求路径一样,只是参数不同
this.$http({
          url: this.$http.adornUrl('/xx/xx'),
          method: 'get',
          params: this.$http.adornParams({  'xx':0,  })
        }).then(({data}) => { })

this.$http({
          url: this.$http.adornUrl('/xx/xx'),
          method: 'get',
          params: this.$http.adornParams({  'xx':1,  })
        }).then(({data}) => { })

**Comment by daxiongYang** [comment]
去Axios官网查找axios.all方法，或者Promise.all也可以。
