### ISSUE TITLE
tab切换页面为什么还要重新刷新呢？

### ISSUE THREAD

**Issue by slyang520** [daxiongYang/renren-fast-vue#6]
tab切换页面为什么还要重新刷新呢？

**Comment by daxiongYang** [comment]
1. 并没有刷新。你可以观察查询条件搜索框中的内容，切换不会被清掉的！
2. 这里看到有发送请求是因为获取列表方法写在activated钩子里面（这个请求是带有查询条件内容的）。如果你想切换tab不重新请求列表数据，可以放在created／mounted钩子里面！
